### ISSUE TITLE
RDS: Document update/upgrade behavior

### ISSUE THREAD

**Issue by flobaader** [pellepelster/solidblocks#15]
Currently the container installs the latest postgres 14 version on alpine linux.
The tasks of a long running VM should be documented, e.g. upgrading the base OS, upgrade the Hetzner RDS container or upgrade to a new major version of postgres.

**Comment by pellepelster** [comment]
since v0.1.18 there is documentation available on how the upgrade path works (https://pellepelster.github.io/solidblocks/rds/index.html#architecture) as well as dedicated images for PostgreSQL 14 and 15 (https://pellepelster.github.io/solidblocks/rds/index.html#versions). Those changes are also reflected in the Hetzner RDS module, see changelog https://github.com/pellepelster/solidblocks/releases/tag/v0.1.18
