### ISSUE TITLE
RDS: Allow to set max connections parameter

### ISSUE THREAD

**Issue by flobaader** [pellepelster/solidblocks#16]
For a postgres database allow to set the max connections parameter

**Comment by pellepelster** [comment]
Setting the max connections parameter should be possible by setting https://postgresqlco.nf/doc/en/param/max_connections/ via https://pellepelster.github.io/solidblocks/hetzner/rds/index.html#input%5c_postgres%5c_extra%5c_config. If this turns out to be a common pattern that is used by many users it may be promoted to a dedicated variable
